[project]
name = 'Blockchain-Based-Financial-Planning-Analysis-Systems'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.decision-support]
path = 'contracts/decision-support.clar'
clarity_version = 2
epoch = 2.5

[contracts.forecasting-coordination]
path = 'contracts/forecasting-coordination.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
